baseurl = "http://wysocki.in/blog/"
languageCode = "en-us"
title = "Jacek Wysocki DevLog"
theme = "hugo-steam-theme"
disqusShortname = "ex00"
paginate = 10

[params]

	title = "Jacek Wysocki DevLog"
	subtitle = "stuff about programming"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "green"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jacek Wysocki"
	bio = "I'm on [Github](//github.com/exu) or [Twitter](https://twitter.com/ex00)"
	description = "LOL"
	location = "" # optional
	twitter = "ex00" # optional
	github = "exu" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"