baseurl = "http://wysocki.in/"
languageCode = "en-us"
title = "Jacek Wysocki DevLog"
theme = "steam"
# theme = "hugo-theme-air"
disqusShortname = "wysocki"
paginate = 10
canonifyurls = false
pygmentsstyle = "monokai"
pygmentsuseclasses = false

[permalinks]
  post = "/:slug"
  til = "/:section/:slug"


[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"


[params]
	title = "Jacek Wysocki DevLog"
	subtitle = "various stuff about programming"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "green"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-1883783-5"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jacek Wysocki"
	bio = "I'm on [Github](//github.com/exu) or [Twitter](https://twitter.com/ex00)"
	description = "I'm developer recently focused on learning Go, Emacs and Archlinux user, father of two lovely children and amateur runner."
	location = "" # optional
	twitter = "ex00" # optional
	github = "exu" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"



[[menu.main]]
    name = "Posts"
    weight = -200
    identifier = "root"
    url = "/"
    pre = "<i class='fa fa-heart-o'></i>"
[[menu.main]]
    name = "Series"
    weight = -90
    url = "/series/"
    pre = "<i class='fa fa-folder-o'></i>"
[[menu.main]]
    name = "Tags"
    weight = -100
    url = "/tags/"
    pre = "<i class='fa fa-star-o'></i>"
[[menu.main]]
    name = "TIL"
    weight = -40
    identifier = "til"
    url = "/til/"
    pre = "<i class='fa fa-thumbs-o-up'></i>"
[[menu.main]]
    name = "Contact"
    weight = -20
    identifier = "contact"
    url = "/contact/"
    pre = "<i class='fa fa-envelope-o'></i>"
